GET http://127.0.0.1:5000/api/users

###

GET http://127.0.0.1:5000/api/user/6c96641e-fbba-47ab-bd7d-8c71ddc1e9a4

###

POST http://127.0.0.1:5000/api/user
content-type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6Imp1YW4ucmFtw61yZXoiLCJyZW1vdGVBZGRyZXNzIjoiOjpmZmZmOjEyNy4wLjAuMSIsInR5cGUiOiJhZG1pbmlzdHJhdG9yIiwiaWF0IjoxNjI3OTEwMDE2LCJleHAiOjE2Mjc5OTQwMTZ9.97-MpdpKJT8CyeZqRZ5lv1vVgW7TEpIRJw_8fVoPf90

login=josemaria.jimenez
&password=jmj1234
&type=user
&first-name=José María
&last-name=Jiménez

###

POST http://127.0.0.1:5000/api/user/authenticate
content-type: application/x-www-form-urlencoded

login=julia.ochoa
&password=Hola1234

###

POST http://127.0.0.1:5000/api/user/authenticate-administrator
content-type: application/x-www-form-urlencoded

login=juan.ramírez
&password=Hola1234

###

GET http://127.0.0.1:5000/api/users 
Content-Type: application/x-www-form-urlencoded 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6Imp1YW4ucmFtw61yZXoiLCJyZW1vdGVBZGRyZXNzIjoiOjpmZmZmOjEyNy4wLjAuMSIsInR5cGUiOiJhZG1pbmlzdHJhdG9yIiwiaWF0IjoxNjI3ODkyNDUzLCJleHAiOjE2Mjc5NzY0NTN9.mIpcf84ezh8wqvHtCfwi0VXXp4LV0qHZR-LPTkAJMeA

###

GET http://127.0.0.1:5000/api/user/6c96641e-fbba-47ab-bd7d-8c71ddc1e9a4
Content-Type: application/x-www-form-urlencoded 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6Imp1YW4ucmFtw61yZXoiLCJyZW1vdGVBZGRyZXNzIjoiOjpmZmZmOjEyNy4wLjAuMSIsInR5cGUiOiJhZG1pbmlzdHJhdG9yIiwiaWF0IjoxNjI3OTEwMDE2LCJleHAiOjE2Mjc5OTQwMTZ9.97-MpdpKJT8CyeZqRZ5lv1vVgW7TEpIRJw_8fVoPf90